# ENSEMBLE METHOD---

In [3]:
import sklearn
print(sklearn.__version__)

1.1.2


In [20]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings ('ignore')

In [21]:
# load iris data sets

iris=load_iris()

#print(iris)
x=iris.data[:,:4]
y=iris.target


# train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

# Bagging

In [22]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100,random_state=42)
# RandomForestClassifier(100).......Default

rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))


1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Boosting

In [23]:
from sklearn.ensemble import AdaBoostClassifier
#AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), *, n_estimators=50, learning_rate=1.0

ad=AdaBoostClassifier()

ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:
from sklearn.ensemble import AdaBoostClassifier

ad=AdaBoostClassifier(n_estimators=50)

ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [14]:
# import Support victor Classifier

from sklearn.svm import SVC
svc=SVC()
# create AdaBoostClassifier object
ad=AdaBoostClassifier(n_estimators=50, base_estimator=svc,algorithm='SAMME')
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.3
[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



In [15]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
# create AdaBoostClassifier object
ad=AdaBoostClassifier(n_estimators=50, base_estimator=svc,algorithm='SAMME')
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.9666666666666667
[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [15]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
# create AdaBoostClassifier object
ad=AdaBoostClassifier(n_estimators=50, base_estimator=svc,algorithm='SAMME')
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.9666666666666667
[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [18]:
from sklearn.ensemble import GradientBoostingClassifier
gd=GradientBoostingClassifier()
gd.fit(x_train,y_train)
gd_pred=gd.predict(x_test)
print(accuracy_score(y_test,gd_pred))
print(confusion_matrix(y_test,gd_pred))
print(classification_report(y_test,gd_pred))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Voting Classifier

In [8]:
from sklearn.ensemble import VotingClassifier

In [28]:
# group / ensemble of models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
estimator=[]
estimator.append(('LR',KNeighborsClassifier()))
estimator.append(('SVC',SVC(gamma='auto',probability=True)))
estimator.append(('DTC',DecisionTreeClassifier()))

In [29]:
estimator

[('LR', KNeighborsClassifier()),
 ('SVC', SVC(gamma='auto', probability=True)),
 ('DTC', DecisionTreeClassifier())]

In [36]:
# voting classifier with hard voting

vot_hard = VotingClassifier(estimators=estimator,voting="hard")
vot_hard.fit(x_train,y_train)
y_pred=vot_soft.predict(x_test)

print(y_pred)
score=accuracy_score(y_test,y_pred)
print('hard voting score %d'% score)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
hard voting score 1


In [35]:
# voting classifier with soft voting

vot_soft = VotingClassifier(estimators = estimator,voting = "soft")
vot_soft.fit(x_train,y_train)
y_pred = vot_soft.predict(x_test)
print(y_pred)

score=accuracy_score(y_test,y_pred)
print('soft voting score %d'% score)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
soft voting score 1


# Ensemble Over there

# Pipe Line

In [42]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

In [44]:
#x,y = make_classification(random_state=0)

#x_train,x_test,y_train,y_test=train_test_split()

pipe=Pipeline([('scaler',StandardScaler()),('svc',SVC())])
pipe.fit(x_train,y_train)
Pipeline(steps=[('scaler',StandardScaler()),('svc',SVC())])
pipe.score(x_test,y_test)

1.0

# Gradient Decscent Algorithm - it is used to reduce the error

In [56]:
# importing libraries

from sklearn import linear_model
from sklearn.datasets import load_boston
from sklearn.linear_model import SGDRegressor
from sklearn.decomposition import PCA
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

import numpy as np
import pandas as pd

# Loading the datasets
X=load_boston()
data=pd.DataFrame(X.data,columns=X.feature_names)
Y=X.target

#Creating a model
pipe =[]
pipe.append(('SC',StandardScaler()))
pipe.append(('PCA',PCA(n_components=8)))
pipe.append(('SGD',SGDRegressor(alpha=0.1,learning_rate='optimal',max_iter=400,penalty='l2')))
model=Pipeline(pipe)

# cross validation score
cv_results=cross_val_score(model,data,Y,cv=5)
msg = "%s: %f (%f)" % ('SGDRegressor',cv_results.mean(), cv_results.std())
print(msg)




SGDRegressor: 0.504684 (0.244393)


In [61]:
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import load_iris
X=load_iris()
data=pd.DataFrame(X.data,columns=X.feature_names)
Y=X.target

# Creating a Model
model=SGDClassifier()

# cross validation score

cv_results=cross_val_score(model,data,Y,cv=5)
msg = "%s: %f (%f)" % ('SGDClassifier',cv_results.mean(), cv_results.std())
print(msg)





SGDClassifier: 0.746667 (0.100222)
